config/routes.rb
Rails.application.routes.draw do

  get    'static_pages/home'  => 'static_pages#home', as: :static_home
  get 'static_pages/contact'

  get    'signup'  => 'users#new',            :as => :signup
  get    'signin'  => "sessions#new",         :as => :signin
  get    'signout' => 'sessions#destroy',     :as => :signout
  get    'aboutus' => 'pics#aboutus',         :as => :aboutus
  resources :payments
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :pics

  root 'users#new'

end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :pics

  mount_uploader :picture, PictureUploader
  validate  :picture_size


  validates_presence_of :name, :email, :message => ": cant be blank"
	validates_length_of :name, :email, :in => 2..80
	validates_uniqueness_of :email, :message => ": This email already exists"
	VALID_EMAIL_REGEX = /\A[\w+\-.]+@[a-z\d\-.]+\.[a-z]+\z/i
	validates :email, format: { with: VALID_EMAIL_REGEX }

 
  validates_presence_of :picture, :message => ": Please upload a picture"



  private

    # Validates the size of an uploaded picture.
    def picture_size
      if picture.size > 2.megabytes
        errors.add(:picture, "should be less than 2MB")
      end
    end

end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

 
  # GET /users
  # GET /users.json
  def index
    @users = User.all
    @user = User.new

  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, :flash => {:success => 'Image was successfully uploaded. We will get back to you within 24 hours.'}}
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name, :email, :picture)
    end

    

   

end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <%= render 'error_messages', object: f.object %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/_img_upload.html.erb
<%= form_for(@user, html: {multipart: true}) do |f| %>
  <%= render 'error_messages', object: f.object %>
  

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :email %><br>
    <%= f.email_field :email %>
  </div>

  <span class="field">

  <%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png'  %><br /><br /><br />
  </span>
  <%= f.submit "Post", class: "btn btn-primary" %>
<% end %>
<br />
<script type="text/javascript">
  $('#user_picture').bind('change', function() {
    size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 2) {
      alert('Maximum file size is 2MB. Please choose a smaller file.');
    }
  });
</script>

app/views/users/edit.html.erb
<h3 style="color:red">You have no access to this page!!</h3>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>
<ul>
<% @users.each do |f| %>
<li>
	<span class="content">
	<%= f.name %>
  <%= image_tag f.picture.url if f.picture? %>
</span><br />
</li>


<% end %>
</ul>

<%= render 'img_upload' %>

app/views/users/new.html.erb
<h1>New User</h1>

<br /><br /><br />
<h4>Please provide your name and email address and upload the image below:</h4>
<br />

<%= render 'img_upload' %>
<br />
<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

 <h3>Dear <%= @user.name %>! </h3><br /><br />

 
 <h5>Please make the  <%= link_to 'Payment here', new_payment_path %></h5>