config/routes.rb
Rails.application.routes.draw do

  get    'static_pages/home'  => 'static_pages#home', as: :static_home
  get 'static_pages/contact'

  get    'signup'  => 'users#new',            :as => :signup
  get    'signin'  => "sessions#new",         :as => :signin
  get    'signout' => 'sessions#destroy',     :as => :signout
  get    'aboutus' => 'pics#aboutus',         :as => :aboutus
  resources :payments
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :pics

  root 'users#new'

end

app/models/pic.rb
class Pic < ActiveRecord::Base

	belongs_to :user

end

app/controllers/pics_controller.rb
class PicsController < ApplicationController
  before_action :set_pic, only: [:show, :edit, :update, :destroy]

  # GET /pics
  # GET /pics.json
  def index
    @pics = Pic.all
  end

  # GET /pics/1
  # GET /pics/1.json
  def show
  end

  # GET /pics/new
  def new
    @pic = Pic.new
  end

  # GET /pics/1/edit
  def edit
  end

  # POST /pics
  # POST /pics.json
  def create
    @pic = current_user.pics.create(pic_params)
    if @pic.save
      flash[:success] = "Picture uploaded successfully!"
      redirect_to users_path
    else
      flash[:error] = "upload the picture again!"
      redirect_to static_home_path
    end
  end

  # PATCH/PUT /pics/1
  # PATCH/PUT /pics/1.json
  def update
    respond_to do |format|
      if @pic.update(pic_params)
        format.html { redirect_to @pic, notice: 'Pic was successfully updated.' }
        format.json { render :show, status: :ok, location: @pic }
      else
        format.html { render :edit }
        format.json { render json: @pic.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /pics/1
  # DELETE /pics/1.json
  def destroy
    @pic.destroy
    respond_to do |format|
      format.html { redirect_to pics_url, notice: 'Pic was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def aboutus
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_pic
      @pic = Pic.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def pic_params
      params.require(:pic).permit(:picture)
    end
end

app/helpers/pics_helper.rb
module PicsHelper
end

app/views/pics/_form.html.erb
<%= form_for(@pic) do |f| %>
  <% if @pic.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@pic.errors.count, "error") %> prohibited this pic from being saved:</h2>

      <ul>
      <% @pic.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :picture %><br>
    <%= f.text_field :picture %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/pics/aboutus.html.erb
Will be updated soon

app/views/pics/edit.html.erb
<h1>Editing Pic</h1>

<%= render 'form' %>

<%= link_to 'Show', @pic %> |
<%= link_to 'Back', pics_path %>

app/views/pics/new.html.erb
<h1>New Pic</h1>

<%= render 'form' %>

<%= link_to 'Back', pics_path %>

app/views/pics/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Picture:</strong>
  <%= @pic.picture %>
</p>

<%= link_to 'Edit', edit_pic_path(@pic) %> |
<%= link_to 'Back', pics_path %>