config/routes.rb
Rails.application.routes.draw do

  get    'static_pages/home'  => 'static_pages#home', as: :static_home
  get 'static_pages/contact'

  get    'signup'  => 'users#new',            :as => :signup
  get    'signin'  => "sessions#new",         :as => :signin
  get    'signout' => 'sessions#destroy',     :as => :signout
  get    'aboutus' => 'pics#aboutus',         :as => :aboutus
  resources :payments
  resources :users
  resources :sessions, :only => [:new, :create, :destroy]
  resources :pics

  root 'users#new'

end

app/models/payment.rb
require 'net/http'
require 'uri'

class Payment < ActiveRecord::Base

  attr_accessor :cardNumber, :cardCVV, :cardExpiryMonth, :cardExpiryYear

  validate :credit_card_api_access, :on => :create
  MERCHANT_ID = "0000992"
  INTEGRATION_URL = "https://gateway.cardstream.com/direct/"

  def request_data
    { 
      :amount => self.amount.to_i,
      :cardNumber => self.cardNumber,
      :cardExpiryMonth => self.cardExpiryMonth.to_i,
      :cardExpiryYear => self.cardExpiryYear.to_i,
      :cardCVV => self.cardCVV.to_i,
      :merchantID => MERCHANT_ID, 
      :action => "SALE", 
      :type => 1,
      :currencyCode => 826,
      :orderRef => "Test purchase",
      :countryCode => 826,
      :returnInternalData => "Y",
      :threeDSRequired => "N"
    }
  end

  def credit_card_api_access
    uri = URI.parse(INTEGRATION_URL)
    http = Net::HTTP.new(uri.host, 443)
    http.use_ssl = true
    req = Net::HTTP::Post.new(uri.request_uri)
    req.set_form_data(request_data)
    response = http.request(req)
    response_hash = Rack::Utils.parse_nested_query response.body
    if response_hash['responseCode'] != "0"
      errors.add(:id, "Payment failed #{response_hash['responseMessage']}")
    else
      self.attributes = strip_cc_response_hash(response_hash)
    end
  end

  def strip_cc_response_hash(hsh)
    hsh.each { |key,value| hsh.delete(key) unless Payment.column_names.include?(key)}
    return hsh
  end


end

app/controllers/payments_controller.rb
class PaymentsController < ApplicationController
  before_action :set_payment, only: [:show, :edit, :update, :destroy]

  # GET /payments
  # GET /payments.json
  def index
    @payments = Payment.all
  end

  # GET /payments/1
  # GET /payments/1.json
  def show
  end

  # GET /payments/new
  def new
    @payment = Payment.new
  end

  # GET /payments/1/edit
  def edit
  end

  # POST /payments
  # POST /payments.json
  def create
    @payment = Payment.new(payment_params)

    respond_to do |format|
      if @payment.save
        format.html { redirect_to @payment, notice: 'Payment was successfully created.' }
        format.json { render :show, status: :created, location: @payment }
      else
        format.html { render :new }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /payments/1
  # PATCH/PUT /payments/1.json
  def update
    respond_to do |format|
      if @payment.update(payment_params)
        format.html { redirect_to @payment, notice: 'Payment was successfully updated.' }
        format.json { render :show, status: :ok, location: @payment }
      else
        format.html { render :edit }
        format.json { render json: @payment.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /payments/1
  # DELETE /payments/1.json
  def destroy
    @payment.destroy
    respond_to do |format|
      format.html { redirect_to payments_url, notice: 'Payment was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_payment
      @payment = Payment.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def payment_params
      params.require(:payment).permit(:amount, :responseCode, :responseMessage, :xref, :amountReceived, :transactionID, :cardNumberMask, :cardTypeCode, :cardType)
    end
end

app/helpers/payments_helper.rb
module PaymentsHelper

  def cc_years
    yrs = []
    year_today = Date.today.strftime("%y").to_i
    year_today.upto(year_today+10).each do |y| yrs << y.to_s;end
    return yrs
  end
  
  def cc_months
    ['01','02','03','04','05','06','07','08','09','10','11','12']
  end
end

app/views/payments/_form.html.erb
<%= form_for @payment, :html => { :class => "form-horizontal payment" } do |f| %>

    <% if @payment.errors.any? %>
    <div id="error_expl" class="panel panel-danger">
      <div class="panel-heading">
        <h3 class="panel-title"><%= pluralize(@payment.errors.count, "error") %> prohibited this payment from being saved:</h3>
      </div>
      <div class="panel-body">
        <ul>
        <% @payment.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
        </ul>
      </div>
    </div>
  <% end %>

  <div class="control-group">
    <%= f.label :amount, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amount, :class => 'form-control' %>
    </div>
    <%= error_span(@payment[:amount]) %>
  </div>
  <div class="control-group">
    <%= f.label :responseCode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :responseCode, :class => 'form-control' %>
    </div>
    <%= error_span(@payment[:responseCode]) %>
  </div>
  <div class="control-group">
    <%= f.label :responseMessage, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :responseMessage, :class => 'form-control' %>
    </div>
    <%= error_span(@payment[:responseMessage]) %>
  </div>
  <div class="control-group">
    <%= f.label :xref, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :xref, :class => 'form-control' %>
    </div>
    <%= error_span(@payment[:xref]) %>
  </div>
  <div class="control-group">
    <%= f.label :amountReceived, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :amountReceived, :class => 'form-control' %>
    </div>
    <%= error_span(@payment[:amountReceived]) %>
  </div>
  <div class="control-group">
    <%= f.label :transactionID, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :transactionID, :class => 'form-control' %>
    </div>
    <%= error_span(@payment[:transactionID]) %>
  </div>
  <div class="control-group">
    <%= f.label :cardNumberMask, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cardNumberMask, :class => 'form-control' %>
    </div>
    <%= error_span(@payment[:cardNumberMask]) %>
  </div>
  <div class="control-group">
    <%= f.label :cardTypeCode, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cardTypeCode, :class => 'form-control' %>
    </div>
    <%= error_span(@payment[:cardTypeCode]) %>
  </div>
  <div class="control-group">
    <%= f.label :cardType, :class => 'control-label' %>
    <div class="controls">
      <%= f.text_field :cardType, :class => 'form-control' %>
    </div>
    <%= error_span(@payment[:cardType]) %>
  </div>


  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
            payments_path, :class => 'btn btn-default' %>

<% end %>

app/views/payments/edit.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.edit', 'Edit %{model}'], :model => model_class.model_name.human.titleize %></h1>
</div>
<%= render :partial => 'form' %>

app/views/payments/index.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.pluralize.titleize %></h1>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th><%= model_class.human_attribute_name(:amount) %></th>
      <th><%= model_class.human_attribute_name(:responseCode) %></th>
      <th><%= model_class.human_attribute_name(:responseMessage) %></th>
      <th><%= model_class.human_attribute_name(:xref) %></th>
      <th><%= model_class.human_attribute_name(:amountReceived) %></th>
      <th><%= model_class.human_attribute_name(:transactionID) %></th>
      <th><%= model_class.human_attribute_name(:cardNumberMask) %></th>
      <th><%= model_class.human_attribute_name(:cardTypeCode) %></th>
      <th><%= model_class.human_attribute_name(:cardType) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @payments.each do |payment| %>
      <tr>
        <td><%= link_to payment.id, payment_path(payment) %></td>
        <td><%= payment.amount %></td>
        <td><%= payment.responseCode %></td>
        <td><%= payment.responseMessage %></td>
        <td><%= payment.xref %></td>
        <td><%= payment.amountReceived %></td>
        <td><%= payment.transactionID %></td>
        <td><%= payment.cardNumberMask %></td>
        <td><%= payment.cardTypeCode %></td>
        <td><%= payment.cardType %></td>
        <td><%=l payment.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_payment_path(payment), :class => 'btn btn-default btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      payment_path(payment),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-xs btn-danger' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_payment_path,
            :class => 'btn btn-primary' %>

app/views/payments/new.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => [:'helpers.titles.new', 'New %{model}'], :model => model_class.model_name.human %></h1>
</div>

<%= form_for @payment, :html => { :class => 'form-horizontal' } do |f| %>
<div>
<% if @payment.errors.any? %>
  <div class="alert alert-error">
    <a class="close" data-dismiss="alert">×</a>
    <% for message in @payment.errors.full_messages %> 
      <%= message %>
    <% end %> 
  </div>
<% end %>
</div>

<div class="control-group">
  <%= f.label :amount, 'Price', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :amount, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :cardNumber,'Card Number', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :cardNumber, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :cardCVV,'CVV', :class => 'control-label' %>
  <div class="controls">
    <%= f.text_field :cardCVV, :class => 'text_field' %>
  </div>
</div>

<div class="control-group">
  <%= f.label :cardExpiryMonth,'Expiry Month', :class => 'control-label' %>
  <div class="controls">
    <%= f.select(:cardExpiryMonth, options_for_select(cc_months)) %>
  </div>
</div>

<div class="control-group">
  <%= f.label :cardExpiryYear,'Expiry Year', :class => 'control-label' %>
  <div class="controls">
    <%= f.select(:cardExpiryYear, options_for_select(cc_years)) %>
  </div>
</div><br /><br />

<div class="form-actions">
  <%= f.submit nil, :class => 'btn btn-primary' %>
  <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
              payments_path, :class => 'btn' %>
</div>
<% end %>

app/views/payments/show.html.erb
<%- model_class = Payment -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human.titleize %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:amount) %>:</strong></dt>
  <dd><%= @payment.amount %></dd>
  <dt><strong><%= model_class.human_attribute_name(:responseCode) %>:</strong></dt>
  <dd><%= @payment.responseCode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:responseMessage) %>:</strong></dt>
  <dd><%= @payment.responseMessage %></dd>
  <dt><strong><%= model_class.human_attribute_name(:xref) %>:</strong></dt>
  <dd><%= @payment.xref %></dd>
  <dt><strong><%= model_class.human_attribute_name(:amountReceived) %>:</strong></dt>
  <dd><%= @payment.amountReceived %></dd>
  <dt><strong><%= model_class.human_attribute_name(:transactionID) %>:</strong></dt>
  <dd><%= @payment.transactionID %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cardNumberMask) %>:</strong></dt>
  <dd><%= @payment.cardNumberMask %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cardTypeCode) %>:</strong></dt>
  <dd><%= @payment.cardTypeCode %></dd>
  <dt><strong><%= model_class.human_attribute_name(:cardType) %>:</strong></dt>
  <dd><%= @payment.cardType %></dd>
</dl>

<%= link_to t('.back', :default => t("helpers.links.back")),
              payments_path, :class => 'btn btn-default'  %>
<%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_payment_path(@payment), :class => 'btn btn-default' %>
<%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              payment_path(@payment),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>